spring:
  reactor:
    context-propagation: auto
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 29092
          enable-observation: true
      bindings:
        hello-out-0:
          destination: hello.in
      default-binder: kafka
  application:
    name: web
  data:
    mongodb:
      database: web

management:
  metrics:
    mongo:
      command:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
server:
  port: 8080

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
